modLoader="javafml"
loaderVersion="[37,)"
license="GPLv3"
issueTrackerURL="https://github.com/CrimsonFluff/Silk-Chests/issues"

[[mods]]
modId="silkytouch"
version="1.17.1-1.0.0"
displayName="Silky Touch"
displayURL="http://crimsonfluff.com/"
updateJSONURL = "https://github.com/CrimsonFluff/Silk-Chests/raw/1.17.1/update.json"
authors="ยง4Crimson_Fluff"
logoFile="logo.png"
description=''' "Silking the un-silkable !" '''
