modLoader="javafml"
loaderVersion="[${loader_version},)"
license="GPLv3"
issueTrackerURL="https://github.com/CrimsonFluff/Silk-Spawners/issues" #optional

[[mods]]
modId="silkytouch"
version="${version}"
displayName="Silky Touch"
displayURL="https://www.curseforge.com/minecraft/mc-mods/crimson-silky-touch"
updateJSONURL="https://github.com/CrimsonFluff/Silk-Chests/raw/1.16.5/update.json"
authors="ยง4Crimson_Fluff"
logoFile="logo.png"
credits=""
description=''' "Silking the un-silkable" '''

[[dependencies.silkytouch]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
  side="BOTH"
[[dependencies.silkytouch]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
